#!/usr/bin/env python3
"""
Visualize cProfile output using snakeviz.

This script loads the profile data generated by profile_main.py
and opens it in snakeviz for interactive visualization.
"""

import subprocess
import sys
from importlib.util import find_spec
from pathlib import Path


def visualize_profile() -> None:
    """Visualize the profile data with snakeviz."""
    profile_file = Path(__file__).resolve().parent / "profile_output.prof"

    # Check if profile file exists
    if not profile_file.is_file():
        print(f"Error: Profile file '{profile_file}' not found.")
        print("Run 'profile_main.py' first to generate the profile data.")
        sys.exit(1)

    # Check if snakeviz is installed
    if find_spec("snakeviz") is None:
        print("snakeviz is not installed.")
        print("Install it with: python -m pip install snakeviz")
        sys.exit(1)

    # Run snakeviz
    try:
        print(f"Opening profile data in snakeviz: {profile_file}")
        # Use subprocess to run snakeviz as a Python module
        subprocess.run([sys.executable, "-m", "snakeviz", str(profile_file)], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error running snakeviz: {e}")
        print("Make sure snakeviz is properly installed in your Python environment.")
        sys.exit(1)
    except FileNotFoundError:
        print("Python executable not found or snakeviz module not available.")
        print("Try installing snakeviz: pip install snakeviz")
        sys.exit(1)


if __name__ == "__main__":
    visualize_profile()
