# Default configuration for Ultimate Analysis
# This file contains the base configuration used when no specific config is provided

application:
  name: "Ultimate Analysis"
  version: "0.1.0"
  debug: false

gui:
  window_width: 1920
  window_height: 1080
  video_folder: "data/processed/dev_data"
  dark_mode: true

models:
  detection_model: "data/models/finetune/object_detection_yolo11l/finetune3/weights/best.pt"
  field_model: "data/models/finetune/field_finder_yolo11x-seg/segmentation_finetune4/weights/best.pt"
  player_id_model: "data/models/finetune/digit_detector_yolo11m/finetune/weights/best.pt"
  input_size: 960
  confidence_threshold: 0.5
  iou_threshold: 0.45

tracking:
  method: "deepsort"  # or "histogram"
  max_age: 30
  min_hits: 3

player_id:
  method: "easyocr"  # or "yolo"
  cache_size: 100
  update_interval: 10

field:
  length: 70.0  # meters
  width: 37.0   # meters
  goal_zone_length: 18.0  # meters
  player_height: 1.85  # meters (for ground plane estimation)

performance:
  min_fps: 10.0
  max_inference_time_ms: 100.0
  max_memory_usage_mb: 2048

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null  # null for console output, or specify file path

data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  models_dir: "data/models" 
  cache_dir: "data/cache"
