# Ultimate Analysis - Default Configuration
# This file contains all default settings for the application

# Application Settings
app:
  name: "Ultimate Analysis"
  version: "0.1.0"
  debug: false
  log_level: "INFO"
  max_file_size_lines: 500

# Video Processing Settings
video:
  supported_formats: [".mp4", ".avi", ".mov", ".mkv", ".wmv"]
  max_fps: 30
  default_fps: 25
  frame_skip: 1
  cache_frames: true
  max_cached_frames: 100

# Model Configuration
models:
  base_path: "data/models"
  detection:
    default_model: "data/models/detection/object_detection_yolo11l/finetune3/weights/best.pt"
    confidence_threshold: 0.5
    nms_threshold: 0.45
    max_detections: 100
    cache_results: true
  
  segmentation:
    default_model: "yolo11l-seg.pt"
    confidence_threshold: 0.6
    mask_alpha: 0.3
    show_raw_masks: false       # Whether to show raw segmentation model output masks
    
    # Morphological operations for mask smoothing
    morphological:
      opening_kernel_size: 5     # Size for noise removal (0 to disable)
      closing_kernel_size: 5    # Size for hole filling (0 to disable)
      fill_holes: false           # Apply flood fill for remaining holes
    
    # Contour calculation and drawings
    contour:
      simplify_epsilon: 0.0001     # Contour simplification factor (fraction of perimeter)
      min_area: 5000             # Minimum contour area to consider
      line_color: [255, 255, 0]  # BGR color for contour lines (yellow)
      point_color: [0, 255, 255] # BGR color for contour points (cyan)
      line_thickness: 3          # Thickness of contour lines
      point_radius: 5            # Radius of contour points
      draw_points: true          # Whether to draw individual contour points
      
      # Contour interpolation parameters
      interpolation:
        enabled: true            # Whether to interpolate contour points for denser sampling
        max_point_distance: 20   # Maximum distance between consecutive points in pixels
        min_point_distance: 3    # Minimum distance to avoid over-densification
      
      # RANSAC line fitting parameters
      ransac:
        enabled: true            # Whether to use RANSAC line fitting instead of contour
        num_lines: 4            # Number of line segments to fit (3-4 for field boundaries)
        distance_threshold: 5.0 # Maximum distance from point to line for inliers
        min_samples: 2          # Minimum number of points needed to fit a line
        max_trials: 20        # Maximum RANSAC iterations per line segment
        line_color: [0, 255, 0] # BGR color for RANSAC lines (green)
        outlier_color: [0, 165, 255] # BGR color for RANSAC outlier points (orange)
        outlier_radius: 6       # Radius for outlier point visualization (increased for visibility)
        show_outliers: true     # Whether to visualize RANSAC outliers (enabled)
        inlier_color: [0, 255, 0] # BGR color for RANSAC inlier points (green)
        inlier_radius: 5        # Radius for inlier point visualization (increased for visibility)
        show_inliers: true      # Whether to visualize RANSAC inliers (enabled)
        
        # Edge filtering parameters
        edge_filtering:
          enabled: true         # Whether to filter points near image edges
          margin: 15           # Distance from edge in pixels to consider as "near edge"
          edge_point_color: [0, 0, 255] # BGR color for filtered edge points (red)
          edge_point_radius: 6  # Radius for edge point visualization (increased for visibility)
          show_edge_points: true # Whether to visualize filtered edge points
  
  tracking:
    default_tracker: "deepsort"
    max_tracks: 300
    track_history_length: 300
    color_pool_size: 50
    
    # DeepSORT specific settings
    max_age: 10              # Frames to keep lost tracks alive
    n_init: 5                # Frames needed to confirm a track
    nms_overlap: 1           # Non-maximum suppression overlap threshold
    max_cosine_distance: 0.2 # Feature similarity threshold
    nn_budget: 100           # Feature budget per class
    
    # Histogram tracking specific settings
    histogram_match_threshold: 0.3  # Minimum similarity for track matching
    histogram_bins: 32              # Number of histogram bins per channel
  
  player_id:
    ocr_enabled: true
    ocr_languages: ["en"]
    ocr_confidence_threshold: 0.7
    cache_player_ids: true
    
    # Jersey number tracking settings
    tracking:
      max_history_length: 30              # Maximum measurements to keep per track
      confidence_decay_factor: 0.95       # Decay factor for old measurements per frame
      spatial_weight_center_bonus: 0.3    # Bonus weight for center-positioned digits
      min_confidence_threshold: 0.1       # Minimum probability to keep in memory
      center_region_width: 0.4            # Width of "center" region (fraction of bbox)
      measurement_weight_recent: 1.0      # Weight for recent measurements
      measurement_weight_old: 0.5         # Weight for old measurements
      probability_smoothing: 0.1          # Smoothing factor for probability updates

# GUI Settings
gui:
  window_title: "Ultimate Analysis"
  window_width: 1920
  window_height: 1080
  theme: "dark"
  auto_save_settings: true
  fps_display: true

# Performance Settings
performance:
  enable_gpu: true
  max_cpu_cores: -1  # -1 means use all available
  memory_limit_mb: 4096
  cache_size_mb: 512
  enable_profiling: false
  profiling_interval_ms: 1000

# Logging Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "logs/ultimate_analysis.log"
  max_file_size_mb: 10
  backup_count: 5

# Paths
paths:
  data_dir: "data"
  models_dir: "data/models"
  cache_dir: "data/cache"
  logs_dir: "logs"
  output_dir: "output"
  temp_dir: "temp"

# Data Directories
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  dev_data_dir: "data/processed/dev_data"
  raw_videos_dir: "data/raw/videos"
  training_dir: "data/raw/training_data"
  dataset_dir: "data/raw/dataset"

# Homography Estimation Settings
homography:
  save_directory: "configs"
  default_params_file: "configs/homography_params.yaml"
  slider_range_main: [-50.0, 50.0]           # Range for H00, H01, H10, H11 (scale/skew/extreme)
  slider_range_perspective: [-0.2, 0.2]      # Range for H20, H21 (perspective/extreme)
  buffer_factor: 1.8                         # Output canvas size multiplier (1.8 = 80% larger)
  output_aspect_ratio: 3.0                   # Height:width ratio for homography output canvas (3.0 = 3:1)
