# Ultimate Analysis - Default Configuration
# This file contains all default settings for the application

# Application Settings
app:
  name: "Ultimate Analysis"
  version: "0.1.0"
  debug: false
  log_level: "INFO"
  max_file_size_lines: 500

# Video Processing Settings
video:
  supported_formats: [".mp4", ".avi", ".mov", ".mkv", ".wmv"]
  max_fps: 30
  default_fps: 25
  frame_skip: 1
  cache_frames: true
  max_cached_frames: 100

# Model Configuration
models:
  base_path: "data/models"
  detection:
    default_model: "data/models/detection/object_detection_yolo11l/finetune3/weights/best.pt"
    confidence_threshold: 0.5
    nms_threshold: 0.45
    max_detections: 100
    cache_results: true
  
  segmentation:
    default_model: "yolo11l-seg.pt"
    confidence_threshold: 0.6
    mask_alpha: 0.3
  
  tracking:
    default_tracker: "deepsort"
    max_tracks: 300
    track_history_length: 300
    color_pool_size: 50
    
    # DeepSORT specific settings
    max_age: 10              # Frames to keep lost tracks alive
    n_init: 5                # Frames needed to confirm a track
    nms_overlap: 1           # Non-maximum suppression overlap threshold
    max_cosine_distance: 0.2 # Feature similarity threshold
    nn_budget: 100           # Feature budget per class
    
    # Histogram tracking specific settings
    histogram_match_threshold: 0.3  # Minimum similarity for track matching
    histogram_bins: 32              # Number of histogram bins per channel
  
  player_id:
    ocr_enabled: true
    ocr_languages: ["en"]
    ocr_confidence_threshold: 0.7
    cache_player_ids: true
    
    # Jersey number tracking settings
    tracking:
      max_history_length: 30              # Maximum measurements to keep per track
      confidence_decay_factor: 0.95       # Decay factor for old measurements per frame
      spatial_weight_center_bonus: 0.3    # Bonus weight for center-positioned digits
      min_confidence_threshold: 0.1       # Minimum probability to keep in memory
      center_region_width: 0.4            # Width of "center" region (fraction of bbox)
      measurement_weight_recent: 1.0      # Weight for recent measurements
      measurement_weight_old: 0.5         # Weight for old measurements
      probability_smoothing: 0.1          # Smoothing factor for probability updates

# GUI Settings
gui:
  window_title: "Ultimate Analysis"
  window_width: 1920
  window_height: 1080
  theme: "dark"
  auto_save_settings: true
  fps_display: true

# Performance Settings
performance:
  enable_gpu: true
  max_cpu_cores: -1  # -1 means use all available
  memory_limit_mb: 4096
  cache_size_mb: 512
  enable_profiling: false
  profiling_interval_ms: 1000

# Logging Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "logs/ultimate_analysis.log"
  max_file_size_mb: 10
  backup_count: 5

# Paths
paths:
  data_dir: "data"
  models_dir: "data/models"
  cache_dir: "data/cache"
  logs_dir: "logs"
  output_dir: "output"
  temp_dir: "temp"

# Data Directories
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  dev_data_dir: "data/processed/dev_data"
  raw_videos_dir: "data/raw/videos"
  training_dir: "data/raw/training_data"
  dataset_dir: "data/raw/dataset"

# Homography Estimation Settings
homography:
  save_directory: "data/homography_params"
  slider_range_main: [-5.0, 5.0]           # Range for H00, H01, H10, H11 (scale/skew)
  slider_range_perspective: [-0.01, 0.01]  # Range for H20, H21 (perspective)
  buffer_factor: 1.5                       # Output canvas size multiplier (1.5 = 50% larger)
