# Default Homography Parameters for Ultimate Analysis
# These parameters define the perspective transformation matrix used in the homography tab
# The transformation matrix is:
# [H00  H01  H02]
# [H10  H11  H12]
# [H20  H21  1.0]

homography_parameters:
  H00: 0.8800000000000026
  H01: 19.880000000000003
  H02: 128.0
  H10: 0.0
  H11: 20.0
  H12: -500.0
  H20: 0.0
  H21: 0.019799999999999998

metadata:
  created_at: "2025-08-26T00:00:00"
  description: "Default identity matrix homography parameters"
  application: "Ultimate Analysis"
  version: "1.0"
