app:
  name: Ultimate Analysis
  version: 0.1.0
  debug: false
  log_level: INFO
  max_file_size_lines: 500
video:
  supported_formats:
  - .mp4
  - .avi
  - .mov
  - .mkv
  - .wmv
  max_fps: 30
  default_fps: 25
  frame_skip: 1
  cache_frames: true
  max_cached_frames: 100
models:
  base_path: data/models
  detection:
    default_model: data/models/detection/object_detection_yolo11l/finetune3/weights/best.pt
    confidence_threshold: 0.5
    nms_threshold: 0.45
    max_detections: 100
    cache_results: true
  segmentation:
    default_model: data/models/segmentation/20250826_1_segmentation_yolo11s-seg_field
      finder.v8i.yolov8/finetune_20250826_092226/weights/best.pt
    confidence_threshold: 0.6
    mask_alpha: 0.3
    show_raw_masks: false
    morphological:
      opening_kernel_size: 5
      closing_kernel_size: 5
      fill_holes: false
    contour:
      simplify_epsilon: 0.0001
      min_area: 5000
      line_color:
      - 255
      - 255
      - 0
      point_color:
      - 0
      - 255
      - 255
      line_thickness: 3
      point_radius: 5
      draw_points: true
      interpolation:
        enabled: true
        max_point_distance: 20
        min_point_distance: 3
      ransac:
        enabled: true
        num_lines: 4
        distance_threshold: 5.0
        min_samples: 2
        max_trials: 20
        line_color:
        - 0
        - 255
        - 0
        outlier_color:
        - 0
        - 165
        - 255
        outlier_radius: 6
        show_outliers: true
        inlier_color:
        - 0
        - 255
        - 0
        inlier_radius: 5
        show_inliers: true
        edge_filtering:
          enabled: true
          margin: 15
          edge_point_color:
          - 0
          - 0
          - 255
          edge_point_radius: 6
          show_edge_points: true
  tracking:
    default_tracker: deepsort
    max_tracks: 300
    track_history_length: 300
    color_pool_size: 50
    max_age: 10
    n_init: 5
    nms_overlap: 1
    max_cosine_distance: 0.2
    nn_budget: 100
    histogram_match_threshold: 0.3
    histogram_bins: 32
  player_id:
    ocr_enabled: true
    ocr_languages:
    - en
    ocr_confidence_threshold: 0.7
    cache_player_ids: true
    tracking:
      max_history_length: 30
      confidence_decay_factor: 0.95
      spatial_weight_center_bonus: 0.3
      min_confidence_threshold: 0.1
      center_region_width: 0.4
      measurement_weight_recent: 1.0
      measurement_weight_old: 0.5
      probability_smoothing: 0.1
    easyocr:
      adjust_contrast: 0.5
      allowlist: 0123456789
      batch_size: 16
      beamWidth: 5
      canvas_size: 2560
      detail: 1
      filter_ths: 0.003
      gpu: true
      height_ths: 0.7
      link_threshold: 0.2
      low_text: 0.3
      mag_ratio: 3.0
      paragraph: false
      slope_ths: 0.1
      text_threshold: 0.4
      width_ths: 0.3
      workers: 0
      x_ths: 1.0
      y_ths: 0.5
      ycenter_ths: 0.5
    preprocessing:
      brightness_beta: -10
      bw_mode: false
      clahe_clip_limit: 3.0
      clahe_grid_size: 8
      colour_mode: true
      contrast_alpha: 1.5
      crop_top_fraction: 0.45
      denoise: false
      enhance_contrast: false
      gaussian_blur: 0
      min_crop_height: 25
      min_crop_width: 25
      resize_absolute_height: 0
      resize_absolute_width: 0
      resize_factor: 2.0
      sharpen: false
      sharpen_strength: 0.15
      upscale: false
      upscale_factor: 1.0
      upscale_target_size: 256
      upscale_to_size: false
gui:
  window_title: Ultimate Analysis
  window_width: 1920
  window_height: 1080
  theme: dark
  auto_save_settings: true
  fps_display: true
performance:
  enable_gpu: true
  max_cpu_cores: -1
  memory_limit_mb: 4096
  cache_size_mb: 512
  enable_profiling: false
  profiling_interval_ms: 1000
  cache_size_frames: 50
  enable_frame_caching: true
  debounce_delay_ms: 100
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file_enabled: true
  file_path: logs/ultimate_analysis.log
  max_file_size_mb: 10
  backup_count: 5
paths:
  data_dir: data
  models_dir: data/models
  cache_dir: data/cache
  logs_dir: logs
  output_dir: output
  temp_dir: temp
data:
  raw_dir: data/raw
  processed_dir: data/processed
  dev_data_dir: data/processed/dev_data
  raw_videos_dir: data/raw/videos
  training_dir: data/raw/training_data
  dataset_dir: data/raw/dataset
homography:
  save_directory: configs
  default_params_file: configs/processing.yaml
  slider_range_main:
  - -100.0
  - 100.0
  slider_range_perspective:
  - -0.2
  - 0.2
  buffer_factor: 1.8
  output_aspect_ratio: 3.0
  current_parameters:
    H00: 3.4000000000000057
    H01: 7.800000000000011
    H02: -2700.0
    H10: 0.0
    H11: 57.80000000000001
    H12: -6000.0
    H20: 0.0
    H21: 0.014800000000000008
homography_optimization:
  learning_rate: 0.001
  max_adjustment: 0.1
  vertical_threshold_degrees: 15.0
  horizontal_threshold_degrees: 15.0
  bottom_alignment_weight: 1.0
  vertical_alignment_weight: 1.0
  horizontal_alignment_weight: 1.0
