# Ultimate Analysis - Training Configuration
# This file contains all settings related to model training

# Detection Model Training Settings
detection:
  augment: false
  batch_size: 0.8
  copy_paste: 0.0
  cosine_lr: false
  epochs: 10
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  imgsz: 960
  learning_rate: 0.01
  mixup: 0.0
  momentum: 0.937
  mosaic: 1.0
  optimizer: SGD
  patience: 10
  weight_decay: 0.0005
  workers: 8

# Segmentation Model Training Settings
segmentation:
  augment: true
  batch_size: 4.0
  copy_paste: 0.0
  cosine_lr: true
  epochs: 300
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  imgsz: 640
  learning_rate: 0.001
  mixup: 0.0
  momentum: 0.937
  mosaic: 1.0
  optimizer: AdamW
  patience: 20
  weight_decay: 0.0005
  workers: 0

# Player ID Model Training Settings
player_id:
  augment: true
  batch_size: 16
  epochs: 100
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0001
  dropout: 0.5
  
# Data Management
data:
  train_split: 0.8
  val_split: 0.15
  test_split: 0.05
  random_seed: 42
  augmentation_factor: 3
  
# Output Settings
output:
  save_models: true
  save_plots: true
  save_results: true
  verbose: true
  model_format: "pt"  # pt, onnx, torchscript
  
# Hardware Settings
hardware:
  device: "auto"  # auto, cpu, cuda, mps
  multi_gpu: false
  fp16: false
  amp: true  # Automatic mixed precision

# Validation Settings
validation:
  interval: 10  # Validate every N epochs
  save_best: true
  early_stopping: true
  min_delta: 0.001
