"""The parameter forms of the EasyOCR tuning tab."""

from ..widgets.parameter_form import Note, Parameter, Section

PREPROCESS_FORM = [
    Parameter(
        "crop_top_fraction", "crop_fraction_spin", "Top Crop Fraction:", "float", 0.1, 1.0, 0.05
    ),
    Parameter("contrast_alpha", "contrast_spin", "Contrast (\u03b1):", "float", 0.1, 3.0, 0.1),
    Parameter("brightness_beta", "brightness_spin", "Brightness (\u03b2):", "int", -100, 100),
    # The kernel size must be odd
    Parameter("gaussian_blur", "blur_spin", "Gaussian Blur (ksize):", "int", 0, 31, 2),
    Section("=== Minimum Crop Size Filtering ==="),
    Parameter(
        "min_crop_width",
        "min_crop_width_spin",
        "Min Crop Width (px):",
        "int",
        5,
        200,
        tooltip="Skip OCR on crops narrower than this width (pixels). \n"
        "Recommended: 1080p=25px, 720p=18px, 480p=12px",
    ),
    Parameter(
        "min_crop_height",
        "min_crop_height_spin",
        "Min Crop Height (px):",
        "int",
        5,
        200,
        tooltip="Skip OCR on crops shorter than this height (pixels). \n"
        "Recommended: 1080p=35px, 720p=25px, 480p=18px",
    ),
    Note("Skip OCR on crops smaller than these dimensions"),
    Section("=== Contrast Enhancement ==="),
    Parameter("enhance_contrast", "enhance_check", "Enable CLAHE Enhancement:", "bool"),
    Parameter(
        "clahe_clip_limit", "clahe_clip_spin", "  \u2192 Clip Limit:", "float", 1.0, 10.0, 0.5
    ),
    Parameter("clahe_grid_size", "clahe_grid_spin", "  \u2192 Grid Size:", "int", 2, 16),
    Section("=== Denoising ==="),
    Parameter("denoise", "denoise_check", "Enable Denoising:", "bool"),
    Section("=== Sharpening ==="),
    Parameter("sharpen", "sharpen_check", "Enable Sharpening:", "bool"),
    Parameter(
        "sharpen_strength",
        "sharpen_strength_spin",
        "  \u2192 Strength:",
        "float",
        0.01,
        1.0,
        0.01,
        3,
    ),
    Section("=== Upscaling ==="),
    Parameter("upscale", "upscale_check", "Enable Upscaling:", "bool"),
    Parameter("upscale_factor", "upscale_factor_spin", "  \u2192 Factor:", "float", 1.0, 8.0, 0.5),
    Parameter("upscale_to_size", "upscale_to_size_check", "  \u2192 Scale to Fixed Size:", "bool"),
    Parameter(
        "upscale_target_size",
        "upscale_target_spin",
        "    \u2192 Target Size (px):",
        "int",
        64,
        1024,
        32,
    ),
    Section("=== Color Processing ==="),
    Parameter("colour_mode", "colour_mode_check", "Color Mode:", "bool"),
    Parameter("bw_mode", "bw_mode_check", "B&W Mode:", "bool"),
    Section("=== Size Adjustment ==="),
    Parameter("resize_factor", "resize_spin", "Resize Factor:", "float", 0.5, 4.0, 0.1),
    Parameter(
        "resize_absolute_width",
        "resize_width_spin",
        "Absolute Width (px):",
        "int",
        0,
        2048,
        32,
        tooltip="Absolute width in pixels (0 = use factor)",
    ),
    Parameter(
        "resize_absolute_height",
        "resize_height_spin",
        "Absolute Height (px):",
        "int",
        0,
        2048,
        32,
        tooltip="Absolute height in pixels (0 = use factor)",
    ),
]

OCR_FORM = [
    Section("=== Detection Parameters ==="),
    Parameter("text_threshold", "text_threshold_spin", "Text Threshold:", "float", 0.1, 1.0, 0.05),
    Parameter("low_text", "low_text_spin", "Low Text:", "float", 0.1, 1.0, 0.05),
    Parameter("link_threshold", "link_threshold_spin", "Link Threshold:", "float", 0.1, 1.0, 0.05),
    Section("=== Geometric Constraints ==="),
    Parameter("width_ths", "width_ths_spin", "Width Threshold:", "float", 0.1, 2.0, 0.1),
    Parameter("height_ths", "height_ths_spin", "Height Threshold:", "float", 0.1, 2.0, 0.1),
    Parameter("x_ths", "x_ths_spin", "X Threshold:", "float", 0.1, 3.0, 0.1),
    Parameter("y_ths", "y_ths_spin", "Y Threshold:", "float", 0.1, 1.0, 0.05),
    Parameter("ycenter_ths", "ycenter_ths_spin", "Y-Center Threshold:", "float", 0.1, 1.0, 0.05),
    Parameter("slope_ths", "slope_ths_spin", "Slope Threshold:", "float", 0.01, 1.0, 0.05),
    Section("=== Image Processing ==="),
    Parameter("canvas_size", "canvas_size_spin", "Canvas Size:", "int", 512, 4096, 256),
    Parameter("mag_ratio", "mag_ratio_spin", "Mag Ratio:", "float", 0.5, 3.0, 0.1),
    Parameter(
        "adjust_contrast", "adjust_contrast_spin", "Adjust Contrast:", "float", 0.0, 2.0, 0.1
    ),
    Parameter("filter_ths", "filter_ths_spin", "Filter Threshold:", "float", 0.001, 0.1, 0.001, 4),
    Section("=== Performance ==="),
    Parameter(
        "workers",
        "workers_spin",
        "Workers:",
        "int",
        0,
        16,
        tooltip="Number of parallel workers (0 = auto)",
    ),
    Parameter("batch_size", "batch_size_spin", "Batch Size:", "int", 1, 32),
    Parameter("beamWidth", "beam_width_spin", "Beam Width:", "int", 1, 20),
    Section("=== Options ==="),
    Parameter("gpu", "gpu_check", "Use GPU:", "bool"),
    Parameter("paragraph", "paragraph_check", "Paragraph Mode:", "bool"),
    Parameter(
        "detail",
        "detail_spin",
        "Detail Level:",
        "int",
        0,
        2,
        tooltip="0=no detail, 1=bbox, 2=polygon",
    ),
    Section("=== Character Filtering ==="),
    Parameter("allowlist", "allowlist_edit", "Allowlist:", "text", placeholder="e.g., 0123456789"),
    Section("=== Additional Options ==="),
]
